### PR TITLE
fixed prop spreading issue in CopyLinkModal.jsx

### LINKED ISSUE #3233: 6 Files - Part D: Prop spreading is forbidden
We just upgraded to the latest version of AirBNB ESLint rules. We have quite a few files which are violating the "Prop spreading is forbidden" rule. These are the ones to work on for this Issue.

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/VoterGuide/VoterGuideBallotItemCompressed.jsx
  28:13  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/VoterGuide/VoterGuideDisplayForList.jsx
  49:52  error  Prop spreading is forbidden  react/jsx-props-no-spreading
  51:59  error  Prop spreading is forbidden  react/jsx-props-no-spreading
  53:61  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Welcome/AddressBoxWelcome.jsx
  109:9  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Welcome/TextBox.jsx
  19:11  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Widgets/CopyLinkModal.jsx
  47:14  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Widgets/PremiumableButton.jsx
  14:15  error  Prop spreading is forbidden  react/jsx-props-no-spreading
  23:15  error  Prop spreading is forbidden  react/jsx-props-no-spreading

An example of what needs to be changed is in the file `/src/js/components/Connect/CurrentFriends.jsx` (Please don't work on this example -- only the files above.):
```
<FriendDisplayForList {...oneFriend} />
```
In this case, we are passing a dict `oneFriend` with several values into `FriendDisplayForList`, and relying on the `...` to break up these variables and pass them individually into `FriendDisplayForList`. Within FriendDisplayForList, we take in these props, all of which come from the `oneFriend` dict:
```
FriendDisplayForList.propTypes = {
  linked_organization_we_vote_id: PropTypes.string,
  mutual_friends: PropTypes.number,
  positions_taken: PropTypes.number,
  voter_we_vote_id: PropTypes.string,
  voter_photo_url_large: PropTypes.string,
  voter_email_address: PropTypes.string,
  voter_display_name: PropTypes.string,
  voter_twitter_handle: PropTypes.string,
};
```

What we need to do are the following steps:
1) Start with file with the root error, ex/ `CurrentFriends.jsx` (see the list at the start of this issue for the ones for you to work on)
2) Find the line with the ESLint error and identify the component we are passing the object into (ex/ `<FriendDisplayForList`).
3) Search the code base for other instances of that object.
4) Go into that component and find `.propTypes` which shows with variables are being brought into the component. Some of them will be from the incoming object (ex/ `oneFriend`), but some of them may be unrelated.
5) Convert the variables in the `propTypes` code to camel case (ex/ instead of `linked_organization_we_vote_id` change it to `linkedOrganizationWeVoteId`)
6) Add incoming variables on the component we are passing the object into. Ex:
```
<FriendDisplayForList 
  linkedOrganizationWeVoteId={oneFriend.linked_organization_we_vote_id}
  mutualFriends={oneFriend.mutual_friends}
  etc...
/>
```
7) Delete the object being "spread"/passed into the component (i.e., `oneFriend` from `<FriendDisplayForList {...oneFriend} />`)

### PR DESCRIPTION
**Pull request by Julian0510**
### What github.com/wevote/WebApp/issues does this fix?
This fixes #3233
### Changes included this pull request?
fixes the prop spreading issue in CopyLinkModal.jsx

### CODE REVIEW

File: src/js/components/Widgets/CopyLinkModal.jsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ export default class CopyLinkModal extends Component {
     }
 
     return (
-      <Modal {...this.props} size="large" aria-labelledby="contained-modal-title-lg">
+      <Modal Cosize="large" aria-labelledby="contained-modal-title-lg">
```
Comment (DaleMcGrew) [inline src/js/components/Widgets/CopyLinkModal.jsx]: Hello @Julian0510, thank you for submitting this pull request. On this line, 'size="large"' needs to remain as is.  The text "Cosize" looks like a typo? The letters "Co" should be removed.

I believe we want the show and onHide props passed into "<Modal" (as opposed to passing into the "<input" around line 53.

File: src/js/components/Widgets/CopyLinkModal.jsx [hunk 2]
```diff
@@ -54,6 +54,8 @@ export default class CopyLinkModal extends Component {
               readOnly="true"
               value={urlBeingShared}
               className="form-control"
+              show={show}
+              onHide={onHide}
```
Comment (DaleMcGrew) [inline src/js/components/Widgets/CopyLinkModal.jsx]: We want these show and onHide props passed into "<Modal" (as opposed to passing into this "<input".

**Review by DaleMcGrew — CHANGES_REQUESTED** [review]
Thank you @Julian0510 for submitting this pull request! My comments are attached.

**Comment by DaleMcGrew** [comment]
👍 Thank you @Julian0510!
